Part A — Concept Application (40%)
1. Create NumPy arrays of different dimensions (1D, 2D, 3D):
○ Perform indexing and slicing operations
○ Extract specific rows, columns, and subarrays
2. Implement basic operations using NumPy (without loops):
○ Element-wise addition, subtraction, multiplication
○ Compute mean, variance, and standard deviation
3. Demonstrate broadcasting:
○ Add a 1D array to a 2D array
○ Multiply a matrix by a scalar and a vector
○ Explain how broadcasting works in each case
4. Implement vectorised operations:
○ Compute square and cube of all elements
○ Replace all negative values with 0
○ Normalize an array (scale values between 0 and 1)
5. Given a dataset (NumPy array):
○ Find top 5 maximum values
○ Compute row-wise and column-wise sums
○ Identify indices of values greater than a threshold

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr3 = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])

print("1D:", arr1)
print("2D:\n", arr2)
print("3D:\n", arr3)

1D: [10 20 30 40 50]
2D:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
print(arr1[2])   
print(arr1[1:4])     
print(arr2[1, 2])   
print(arr2[1, :])   
print(arr2[:, 1])    
print(arr2[0:2, 1:3]) 
print(arr3[0, :, :])  

30
[20 30 40]
6
[4 5 6]
[2 5 8]
[[2 3]
 [5 6]]
[[1 2]
 [3 4]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  
print(a - b)  
print(a * b)  
data = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(data))
print("Variance:", np.var(data))
print("Std Dev:", np.std(data))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
Mean: 30.0
Variance: 200.0
Std Dev: 14.142135623730951


In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print(A + B)

[[11 22 33]
 [14 25 36]]


In [5]:
print(A * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [6]:
v = np.array([1, 2, 3])
print(A * v)

[[ 1  4  9]
 [ 4 10 18]]


In [ ]:
arr = np.array([-2, -1, 0, 1, 2, 3])

print(arr**2)
print(arr**3)

arr[arr < 0] = 0
print(arr)

data = np.array([10, 20, 30, 40])

normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized)

[4 1 0 1 4 9]
[-8 -1  0  1  8 27]
[0 0 0 1 2 3]
[0.         0.33333333 0.66666667 1.        ]


In [ ]:
data = np.array([[10, 50, 30],
                 [60, 20, 90],
                 [40, 70, 80]])

print(np.sort(data.flatten())[-5:])

print(np.sum(data, axis=1))

print(np.sum(data, axis=0))

indices = np.where(data > 50)
print(indices)

[50 60 70 80 90]
[ 90 170 190]
[110 140 200]
(array([1, 1, 2, 2], dtype=int64), array([0, 2, 1, 2], dtype=int64))
