Prompt:
Explain NumPy broadcasting and vectorisation with practical Python examples.
LLM:
CHatGpt
Output:

Here’s a precise, interview-ready explanation of NumPy broadcasting and vectorisation, with practical Python examples and clear intuition.

📌 1. NumPy Broadcasting
🔍 Definition

Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array without copying data.

⚙️ Broadcasting Rules

Two arrays are compatible if:

Their dimensions are equal OR

One of them is 1

Comparison happens from right to left (trailing dimensions).

✅ Example 1 — 1D + 2D Array

In [1]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print(A + B)

[[11 22 33]
 [14 25 36]]


💡 What happens internally:

A.shape = (2, 3)

B.shape = (3,) → treated as (1,3)

NumPy expands B to:

In [2]:
[[10, 20, 30],
 [10, 20, 30]]

[[10, 20, 30], [10, 20, 30]]

✅ Output:
[[11 22 33]
 [14 25 36]]

✅ Example 2 — Scalar Broadcasting

In [3]:
print(A * 2)

[[ 2  4  6]
 [ 8 10 12]]


👉 Scalar 2 is applied to every element:

[[ 2  4  6]
 [ 8 10 12]]
✅ Example 3 — Column Broadcasting

In [4]:
C = np.array([[1],
              [2]])

print(A + C)

[[2 3 4]
 [6 7 8]]


Shapes:

A → (2,3)

C → (2,1)

C expands across columns:

[[1,1,1],
 [2,2,2]]
Output:
[[2 3 4]
 [6 7 8]]
🧠 Key Insight

Broadcasting avoids:

Writing loops

Creating unnecessary copies
→ Memory efficient + faster

⚡ 2. NumPy Vectorisation
🔍 Definition

Vectorisation means performing operations on entire arrays at once instead of iterating element-by-element using loops.

❌ Without Vectorisation (Slow)

In [5]:
arr = np.array([1, 2, 3, 4, 5])

result = []
for x in arr:
    result.append(x ** 2)

print(result)

[1, 4, 9, 16, 25]


✅ With Vectorisation (Fast)

In [6]:
result = arr ** 2
print(result)

[ 1  4  9 16 25]


👉 Entire operation happens in one step (C-level execution)

✅ Example 1 — Element-wise Operations

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


✅ Example 2 — Conditional Vectorisation

In [8]:
arr = np.array([-3, -1, 2, 4])

arr[arr < 0] = 0
print(arr)

[0 0 2 4]


👉 Replaces all negatives without loops

✅ Example 3 — Normalization

In [9]:
data = np.array([10, 20, 30, 40])

normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized)

[0.         0.33333333 0.66666667 1.        ]


⚡ Performance Comparison

In [10]:
import time

large = np.random.rand(1_000_000)

# Loop
start = time.time()
s = 0
for x in large:
    s += x
print("Loop:", time.time() - start)

# Vectorised
start = time.time()
s = np.sum(large)
print("NumPy:", time.time() - start)

Loop: 0.14820432662963867
NumPy: 0.0


👉 NumPy is significantly faster because:

Uses optimized C backend

Avoids Python interpreter overhead

Uses SIMD (parallel CPU operations)

🔗 Broadcasting vs Vectorisation (Core Difference)
Concept	Broadcasting	Vectorisation
Purpose	Shape compatibility	Speed & efficiency
Works on	Different-sized arrays	Same/different arrays
Eliminates loops?	Yes	Yes
Example	(2×3) + (3,)	arr²
🎯 Final Intuition

Broadcasting = “shape alignment trick”

Vectorisation = “no loops, pure array math”

Together, they enable:

Clean code

High performance

Scalable numerical computing (ML, DL, data science)

If you want next:

🔥 Advanced broadcasting tricks (3D tensors, ML use cases)

📊 Real dataset examples (Pandas + NumPy combined)

🧠 Interview-level tricky questions

Just tell me 👍